# Generated by Django 3.1.7 on 2021-03-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vlogUser',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='myapp.vloguser'),
        ),
        migrations.AddField(
            model_name='posts',
            name='uzer',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='myapp.vloguser'),
        ),
    ]
