# Generated by Django 3.1.7 on 2021-03-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210305_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vlogUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vloguser'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vloguser'),
        ),
    ]
